# Generated by Django 3.0.2 on 2020-01-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Tutee', max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('subjects', models.CharField(help_text='Subjects', max_length=200)),
                ('timeslot', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Tutor', max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('grade', models.CharField(max_length=5)),
                ('subjects', models.CharField(help_text='Subjects', max_length=200)),
                ('timeslot', models.DateTimeField()),
                ('tutee', models.ManyToManyField(to='catalog.Tutee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
