# Generated by Django 3.0.2 on 2020-01-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='tutee',
        ),
        migrations.AddField(
            model_name='tutee',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='tutor',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='tutee',
            name='timeslot',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='timeslot',
            field=models.TimeField(),
        ),
    ]
